# For Pico 1 (RP2040):
#[build]
#target = "thumbv6m-none-eabi"

# For Pico 2 (RP2350), replace above with:
[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
EMBASSY_USB_MAX_INTERFACE_COUNT = "8"
EMBASSY_USB_MAX_HANDLER_COUNT = "8"
